[build]
  command = "npm run build"
  publish = "public"
  functions = "api"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"